config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  resources :recipes do
    collection do
      get "random"
      get "favorite"
    end
  end
  resources :ingredients, only: [], param: :index do
    member do
      delete "(:id)" => "ingredients#destroy", as: ""
      post "/" => "ingredients#create"
    end
  end
  resources :products
  resources :comments
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "recipes#index", as: :authenticated_root
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
  get "home/index"
  root "home#index"
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :products, through: :ingredients
  accepts_nested_attributes_for :ingredients,
    reject_if: :all_blank, allow_destroy: true

  before_save :find_or_create_products

  paginates_per 20

  validates :title, presence: true, length: { maximum: 40 }
  validates :body, presence: true, length: { maximum: 200 }

  default_scope -> { order(created_at: :desc) }
  scope :random, -> { offset(rand(Recipe.count)).take }
  scope :favorite, -> (user) { joins(:likes).where(likes: { user_id: user.id }) }

  private

    def find_or_create_products
      self.ingredients.each do |ingredient|
        ingredient.product = Product.find_or_create_by(name: ingredient.product.name)
      end
    end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @show_clear = true unless params[:q].blank?
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).page(params[:page])
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @comment = current_user.comments.build
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build.build_product
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_url, notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated."
    else
      redirect_to edit_recipe_path(@recipe), alert: "Recipe wasn't saved. #{@recipe.errors.full_messages.first}"
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: "Recipe was successfully destroyed."
  end

  # TO-DO #move to RandomRecipesController
  def random
    redirect_to recipe_path(Recipe.random)
  end

  def favorite
    @show_clear = true unless params[:q].blank?
    @favorite = Recipe.favorite(current_user)
    @q = @favorite.ransack(params[:q])
    @recipes = @q.result(distinct: true).page(params[:page])
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(
        :title, :body, :image,
        ingredients_attributes: [:id, :amount, :_destroy, product_attributes: [:name]])
    end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/recipes/_back_button.html.erb
<div class="back-button mb-5">
  <%= link_to recipes_path, class: "d-flex link-dark" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left me-3" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
    </svg>
    <h5 class="my-auto">Back to recipes</h5>
  <% end %>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
  <div class="mb-3">
    <%= image_tag f.object.image_url, class: "w-100" if f.object.image.present? %>
    <%= f.hidden_field :image, value: f.object.cached_image_data %>
    <label for="formFile" class="form-label">Add a photo of your recipe</label>
    <%= f.file_field :image, class: "form-control", id: "formFile" %>
  </div>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>
  <div class="d-flex justify-content-between mt-5">
    <h4>Ingredients</h4>
    <%= f.submit "Add ingredient", 
      formaction: ingredient_path(@recipe.ingredients.size), 
      formmethod: :post, 
      formnovalidate: true, 
      id: "add-ingredient",
      class: "btn btn-primary" %>
  </div>
  <div id="ingredients" class="my-3">
    <%= f.simple_fields_for :ingredients do |ingredients_form| %>
      <%= render "ingredients/form", form: ingredients_form %>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/_like_button.html.erb
<% unless current_user.liked?(recipe.id) %>
  <%= button_to(likes_path(likeable_id: recipe.id, likeable_type: recipe.class.name), method: :post, class: "btn btn-primary me-2") do %>
    <i class="bi bi-heart-fill"></i>
    <span>Like</span>
  <%end%>
<%else%>
  <%= button_to(like_path(recipe.likes.find_by(user_id: current_user.id)), method: :delete, class: "btn btn-primary me-2") do %>
    <i class="bi bi-heart-fill"></i>
    <span>Unlike</span>
  <%end%>
<%end%>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="col-6 col-sm-3 mb-3">
  <div class="card border">
    <a href="<%= recipe_path(recipe) %>" class="text-decoration-none link-dark">
      <div class="image-container position-relative rounded overflow-hidden" style="height: 180px;">
        <%= render "recipe_image", recipe: recipe %>
        <% if current_user.recipes.include? recipe %>
          <div class="bg-light opacity-75 position-absolute  p-2" style="top: 0; right: 0;">
            <%= render "shared/edit_delete_buttons", model: recipe %>
          </div>
        <%end%>
      </div>
      <div class="card-body mt-2">
        <h5><%= recipe.title %></h5>
        <%= render "recipe_stats", recipe: recipe%>
      </div>
    </a>
  </div>
</div>

app/views/recipes/_recipe_image.html.erb
<% if recipe.image %>
  <%= image_tag recipe.image_url, class: "w-100 z-index-2"%>
<%else%>
  <%= image_tag "food", class: "w-100"%>
<%end%>

app/views/recipes/_recipe_stats.html.erb
<div class="text-secondary d-flex align-items-center">
  <span class="me-2">
    <i class="bi bi-heart-fill"></i>
    <%= recipe.likes.count%>
  </span>
  <span> | </span>
  <span class="ms-2">
    <i class="bi bi-chat-fill"></i>
    <%= recipe.comments.count%>
  </span>
</div>

app/views/recipes/_search_field.html.erb
<div class = "search mb-5">
  <%= search_form_for @q, url: path, class: "d-flex" do |f| %>
    <div class="input-group  me-3" style="width:400px">
      <%= f.text_field :title_or_ingredients_product_name_cont, placeholder: "Search for recipes...", class: "form-control shadow-none", autocomplete: "off" %>
      <% if @show_clear %>
        <%= link_to "Clear", request.path, class: "btn btn-outline-danger" %>
      <% end %>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="w-50 m-auto">
  <%= render "back_button" %>
  <h1>Editing recipe</h1>
  <%= render "form", recipe: @recipe %>
</div>

app/views/recipes/favorite.html.erb
<div class="d-flex justify-content-between mb-3">
  <h1>Favorite recipes</h1>
  <div class="d-flex align-items-center">
  </div>
</div>

<%= render "search_field", path: favorite_recipes_path %>

<div id="recipes" class="row">
  <%= render @recipes %>
</div>
<%= paginate @recipes %>

app/views/recipes/index.html.erb
<div class="d-flex justify-content-between mb-3">
  <h1>Recipes</h1>
  <div class="d-flex align-items-center">
    <%= render "shared/random_button" %>
    <%= button_to "New recipe", new_recipe_path, method: :get, class: "btn btn-primary me-3" %>
  </div>
</div>

<%= render "search_field", path: recipes_path %>

<div id="recipes" class="row">
  <%= render @recipes %>
</div>
<%= paginate @recipes %>

app/views/recipes/new.html.erb
<div class="w-50 m-auto">
  <%= render "back_button" %>
  <h1>New recipe</h1>
  <%= render "form", recipe: @recipe %>
</div>

app/views/recipes/show.html.erb
<div class="m-auto">
  <div class="d-flex justify-content-between">
    <%= render "back_button" %>
    <div class="action-buttons d-flex">
      <%= render "shared/random_button" %>
      <%= render "like_button", recipe: @recipe%>
      <% if current_user.recipes.include? @recipe %>
        <%= button_to "Edit", edit_recipe_path(@recipe), method: :get, class: "btn btn-primary me-2" %>
        <%= button_to "Delete", @recipe, method: :delete, class: "btn btn-primary", form: { data: { turbo_confirm: "Are you sure?" } } %>
      <%end%>
    </div>
  </div>
  <div class ="row mt-5">
    <div class="col-sm-7">
      <div class="recipe-description">
        <h1 class="mb-3"><%= @recipe.title %></h1>
        <p class="text-secondary">Created by <%= @recipe.user.name%></p>
        <%= render "recipe_stats", recipe: @recipe%>
        <h5 class="mt-5">Description:</h5>
        <%= simple_format(@recipe.body) %>
      </div>
      <div class="recipe-ingredients mb-5">
        <h5>Ingredients:</h5>
        <% @recipe.ingredients.each do |i| %>
          <%= i.product.name %> - <%= i.amount%><br>
        <%end%>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="image-container rounded overflow-hidden", style="max-height: 500px;">
        <%= render "recipe_image", recipe: @recipe%>
      </div>
    </div>
  </div>
  <div>
    <div class="col-sm-7 comments">
      <h5>Comments:</h5>
      <%= render "comments/form", recipe: @recipe%>
      <%= render @recipe.comments%>
    </div>
  </div>
</div>