config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  resources :recipes do
    collection do
      get "random"
      get "favorite"
    end
  end
  resources :ingredients, only: [], param: :index do
    member do
      delete "(:id)" => "ingredients#destroy", as: ""
      post "/" => "ingredients#create"
    end
  end
  resources :products
  resources :comments
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "recipes#index", as: :authenticated_root
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
  get "home/index"
  root "home#index"
end

app/views/shared/_edit_delete_buttons.html.erb
<%= link_to edit_polymorphic_path(model), class: "link-dark me-2" do %>
  <i class="bi bi-pencil-fill"></i>
<%end%>
<%= link_to polymorphic_path(model), class: "link-dark", data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } do %>
  <i class="bi bi-x-lg"></i>
<%end%>

app/views/shared/_flashes.html.erb
<% if flash[:success]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:success] %>
  </div>
<%end%>
<% if flash[:notice]%>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
<%end%>
<% if flash[:alert]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert]  %>
  </div>
<%end%>
<% if flash[:session]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:session]  %>
  </div>
<%end%>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
  <div class= "container">
    <div>
      <%= link_to(root_path, class: "navbar-brand h1") do %>
        WTFood
        <%= image_tag "logo", size: "40" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn disabled" href="#">Products</a>
        </li>
        <li class="nav-item">
          <%= link_to "Favorite", favorite_recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <%= link_to "Profile", edit_user_path(current_user), class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_random_button.html.erb
<%= button_to "Random recipe", random_recipes_path, method: :get, class: "btn btn-primary me-3" %>